### PR TITLE
Make ready for npm publishing.

### PR DESCRIPTION
**Pull request by AaronLlanos**
Move package json to top level dir. 
Correct the main file. (can be changed)
Made copy proper dirname into the setup instead of hardcoded windows file extension

### CODE REVIEW

**Comment by Fohlen** [comment]
Hey @AaronLlanos good work so far. Here is my improvement suggestions
- the `release` folder should better be called `dist` since that's what the vast majority of packages do
- you should add a `version` parameter to your `package.json`
- you should add a `git tag` once the release is made
- this will allow for `npm` to directly link your repository at `kekulegit#version`
- it would be greatly appreciated if the official `README.md` is improved, since that will be shown on `npm` when installed

**Comment by AaronLlanos** [comment]
@Fohlen I agree with you. But, I am not sure what will be changed if we were to rename folders in the project. Maybe that's something @partridgejiang can comment on/do? I would also like for him to update the README as this is a project I don't know much about. I just jumped in but really want this to be pushed through to NPM so I can get it bundled in my production builds.

**Comment by AaronLlanos** [comment]
@partridgejiang Before you merge this PR, would you like me to make most of the changes @Fohlen has mentioned here?

**Comment by partridgejiang** [comment]
Sure and thanks a lot for the excellent work.

**Comment by partridgejiang** [comment]
I myself have some problems in opening GitHub site these days, and may update the project in few days.

**Comment by partridgejiang** [comment]
Thanks a lot for @AaronLlanos and @Fohlen, the package has now been published on npmjs.org.

**Pull request merged**
